/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omp
 */
public class Server_GUI extends javax.swing.JFrame {
    
    private Server server;
    /**
     * Creates new form Server_GUI
     */
    public Server_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        serverIdLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        threadsTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        requestsTextField = new javax.swing.JTextField();
        waitLabel = new javax.swing.JLabel();
        runningPanel = new javax.swing.JPanel();
        threadPanel = new javax.swing.JPanel();
        thread1Panel = new javax.swing.JPanel();
        t1ProcessingLabel = new javax.swing.JLabel();
        t1CountDownLabel = new javax.swing.JLabel();
        thread2Panel = new javax.swing.JPanel();
        t2ProcessingLabel = new javax.swing.JLabel();
        t2CountDownLabel = new javax.swing.JLabel();
        thread3Panel = new javax.swing.JPanel();
        t3ProcessingLabel = new javax.swing.JLabel();
        t3CountDownLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientMessageTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        monitorPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addressTextField1 = new javax.swing.JTextField();
        portTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        monitorMessageTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        heartBeatButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverIdLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serverIdLabel.setText("Server id: (not assigned yet)");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverIdLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverIdLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        bodyPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Monitor connection");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Port");

        portTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        portTextField.setText("3001");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("/");

        addressTextField.setEditable(false);
        addressTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTextField.setText("127.0.0.1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thread to process client requests:");

        threadsTextField.setEditable(false);
        threadsTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        threadsTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        threadsTextField.setText("3");
        threadsTextField.setHorizontalAlignment(SwingConstants.RIGHT);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Maximum requests: (not implemented)");

        requestsTextField.setEditable(false);
        requestsTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        requestsTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        requestsTextField.setText("5");
        threadsTextField.setHorizontalAlignment(SwingConstants.RIGHT);

        waitLabel.setText("connecting please stand by ...");
        waitLabel.setVisible(false);

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(startPanelLayout.createSequentialGroup()
                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(startPanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel4))))
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addComponent(requestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(threadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(waitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waitLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        bodyPanel.add(startPanel, "card2");

        threadPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        threadPanel.setMaximumSize(new java.awt.Dimension(539, 223));
        threadPanel.setMinimumSize(new java.awt.Dimension(539, 223));
        threadPanel.setPreferredSize(new java.awt.Dimension(539, 223));

        thread1Panel.setBackground(new java.awt.Color(204, 255, 204));
        thread1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thread 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        thread1Panel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        thread1Panel.setMaximumSize(new java.awt.Dimension(172, 100));
        thread1Panel.setMinimumSize(new java.awt.Dimension(172, 100));
        thread1Panel.setPreferredSize(new java.awt.Dimension(172, 100));

        t1ProcessingLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t1ProcessingLabel.setText("IDLE - waiting for requests");

        t1CountDownLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t1CountDownLabel.setText("Done in ... seconds");
        t1CountDownLabel.setVisible(false);

        javax.swing.GroupLayout thread1PanelLayout = new javax.swing.GroupLayout(thread1Panel);
        thread1Panel.setLayout(thread1PanelLayout);
        thread1PanelLayout.setHorizontalGroup(
            thread1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread1PanelLayout.createSequentialGroup()
                .addGroup(thread1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1ProcessingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t1CountDownLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        thread1PanelLayout.setVerticalGroup(
            thread1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1ProcessingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t1CountDownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        thread2Panel.setBackground(new java.awt.Color(204, 255, 204));
        thread2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thread 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        thread2Panel.setMaximumSize(new java.awt.Dimension(172, 100));
        thread2Panel.setMinimumSize(new java.awt.Dimension(172, 100));
        thread2Panel.setPreferredSize(new java.awt.Dimension(172, 100));

        t2ProcessingLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t2ProcessingLabel.setText("IDLE - waiting for requests");

        t2CountDownLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t2CountDownLabel.setText("Done in ... seconds");
        t2CountDownLabel.setVisible(false);

        javax.swing.GroupLayout thread2PanelLayout = new javax.swing.GroupLayout(thread2Panel);
        thread2Panel.setLayout(thread2PanelLayout);
        thread2PanelLayout.setHorizontalGroup(
            thread2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread2PanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(thread2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t2CountDownLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t2ProcessingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        thread2PanelLayout.setVerticalGroup(
            thread2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t2ProcessingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(t2CountDownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        thread3Panel.setBackground(new java.awt.Color(204, 255, 204));
        thread3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thread 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        thread3Panel.setMaximumSize(new java.awt.Dimension(172, 100));
        thread3Panel.setMinimumSize(new java.awt.Dimension(172, 100));
        thread3Panel.setPreferredSize(new java.awt.Dimension(172, 100));

        t3ProcessingLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t3ProcessingLabel.setText("IDLE - waiting for requests");

        t3CountDownLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t3CountDownLabel.setText("Done in ... seconds");
        t3CountDownLabel.setVisible(false);

        javax.swing.GroupLayout thread3PanelLayout = new javax.swing.GroupLayout(thread3Panel);
        thread3Panel.setLayout(thread3PanelLayout);
        thread3PanelLayout.setHorizontalGroup(
            thread3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t3ProcessingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
            .addComponent(t3CountDownLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        thread3PanelLayout.setVerticalGroup(
            thread3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t3ProcessingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t3CountDownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        clientMessageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Message"
            }
        ));
        jScrollPane2.setViewportView(clientMessageTable);
        if (clientMessageTable.getColumnModel().getColumnCount() > 0) {
            clientMessageTable.getColumnModel().getColumn(0).setMinWidth(100);
            clientMessageTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            clientMessageTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Client Message Log");

        javax.swing.GroupLayout threadPanelLayout = new javax.swing.GroupLayout(threadPanel);
        threadPanel.setLayout(threadPanelLayout);
        threadPanelLayout.setHorizontalGroup(
            threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(threadPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(threadPanelLayout.createSequentialGroup()
                        .addComponent(thread1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(thread2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(thread3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        threadPanelLayout.setVerticalGroup(
            threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threadPanelLayout.createSequentialGroup()
                .addGroup(threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thread2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(thread3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(thread1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        monitorPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Monitor connection");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("/");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Port");

        addressTextField1.setEditable(false);
        addressTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTextField1.setText("127.0.0.1");

        portTextField1.setEditable(false);
        portTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        portTextField1.setText("3001");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address");

        monitorMessageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Message"
            }
        ));
        jScrollPane1.setViewportView(monitorMessageTable);
        if (monitorMessageTable.getColumnModel().getColumnCount() > 0) {
            monitorMessageTable.getColumnModel().getColumn(0).setMinWidth(100);
            monitorMessageTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            monitorMessageTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Monitor Message Log");

        heartBeatButton.setText("monitor HeartBeat");

        javax.swing.GroupLayout monitorPaneLayout = new javax.swing.GroupLayout(monitorPane);
        monitorPane.setLayout(monitorPaneLayout);
        monitorPaneLayout.setHorizontalGroup(
            monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(monitorPaneLayout.createSequentialGroup()
                            .addComponent(addressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(portTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(monitorPaneLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel8)
                            .addGap(49, 49, 49)
                            .addComponent(jLabel10))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(heartBeatButton))
                .addGap(18, 18, 18)
                .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monitorPaneLayout.setVerticalGroup(
            monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monitorPaneLayout.createSequentialGroup()
                        .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monitorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(portTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(addressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(heartBeatButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout runningPanelLayout = new javax.swing.GroupLayout(runningPanel);
        runningPanel.setLayout(runningPanelLayout);
        runningPanelLayout.setHorizontalGroup(
            runningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(threadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addComponent(monitorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        runningPanelLayout.setVerticalGroup(
            runningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runningPanelLayout.createSequentialGroup()
                .addComponent(threadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monitorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.add(runningPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        waitLabel.setVisible(true);
        // start server
        int port = Integer.parseInt(portTextField.getText());
        int threads = Integer.parseInt(threadsTextField.getText());
        new Thread(() -> this.server.connect(port, threads)).start();

        // change panels
        bodyPanel.removeAll();
        bodyPanel.add(runningPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        portTextField1.setText(String.valueOf(port));
    }//GEN-LAST:event_connectButtonActionPerformed

    public void addClientMessage(String msg){
        Object[] row = { msg.split("\\|")[0] , msg.substring(msg.indexOf("|")+1)};      // sender and message
        DefaultTableModel model = (DefaultTableModel) clientMessageTable.getModel();
        model.addRow(row);
    }
    
    public void addMonitorMessage(String msg){
        Object[] row = { msg.split("\\|")[0] , msg.substring(msg.indexOf("|")+1)};      // sender and message
        DefaultTableModel model = (DefaultTableModel) monitorMessageTable.getModel();
        model.addRow(row);
    }
    
    
    public void blink(){
        Runnable blinkRunnable = new Runnable() {
            @Override
            public void run() {
                try {
                    heartBeatButton.setSelected(true);
                    Thread.sleep(200);
                    heartBeatButton.setSelected(false);
                } catch (InterruptedException ex) {
                    System.err.println("Error with hearBeat button");
                    Logger.getLogger(Server_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }    
        };  
        Thread blinkThread = new Thread(blinkRunnable);
        blinkThread.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        Server_GUI server_GUI = new Server_GUI();
        server_GUI.setVisible(true);
        Server server = new Server(server_GUI);
        server_GUI.server = server;
        System.out.println("Server");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField addressTextField1;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JTable clientMessageTable;
    private javax.swing.JButton connectButton;
    public javax.swing.JRadioButton heartBeatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable monitorMessageTable;
    private javax.swing.JPanel monitorPane;
    private javax.swing.JTextField portTextField;
    private javax.swing.JTextField portTextField1;
    private javax.swing.JTextField requestsTextField;
    private javax.swing.JPanel runningPanel;
    public javax.swing.JLabel serverIdLabel;
    private javax.swing.JPanel startPanel;
    public javax.swing.JLabel t1CountDownLabel;
    public javax.swing.JLabel t1ProcessingLabel;
    public javax.swing.JLabel t2CountDownLabel;
    public javax.swing.JLabel t2ProcessingLabel;
    public javax.swing.JLabel t3CountDownLabel;
    public javax.swing.JLabel t3ProcessingLabel;
    public javax.swing.JPanel thread1Panel;
    public javax.swing.JPanel thread2Panel;
    public javax.swing.JPanel thread3Panel;
    private javax.swing.JPanel threadPanel;
    private javax.swing.JTextField threadsTextField;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
